sine_reconstruction_publisher:
  ros__parameters:
    bram_uio_number: 1
    bram_size: 4096

mag_sample_publisher:
  ros__parameters:
    bram_uio_number: 0
    bram_size: 8192

/**:
  ros__parameters:
    video_device: "/dev/video0"
    framerate: 10.0
    io_method: "mmap"
    frame_id: "camera"
    pixel_format: "yuyv"
    image_width: 640
    image_height: 480
    camera_name: "test_camera"
    camera_info_url: "package://usb_cam/config/camera_info.yaml"

    world_frame_id: "world"
    drone_frame_id: "drone"

    filename: "~/mag_samples.txt"

    n_periods: 20

    max_n_samples: 200

    vector_parallel_dot_prod_thresh: 0.95

    kf_q: 0.999
    kf_r: 0.001

    I_min: 100
    I_max: 1000
    xyz_min: -10
    xyz_max: 10



