sine_reconstruction_publisher:
  sine_reconstruction_publisher:
    ros__parameters:
      bram_uio_number: 1
      bram_size: 16384

mag_sample_publisher:
  mag_sample_publisher:
    ros__parameters:
      bram_uio_number: 0
      bram_size: 16384
      n_periods: 20
      sine_reconstruction_method: 2

gain_controller:
  gain_controller:
    ros__parameters:
      max_gain_step: 63
      initial_gain_step: 0
      control_gain_uio_ref_name: "controlgain"

gain_computer:
  gain_computer: 
    ros__parameters:
      max_gain_step: 63
      initial_gain_step: 0
      gain_per_step: 7.8125
      amplitude_range: 2048.
      target_norm_amplitude: 0.5
      hysteresis_upper_norm_threshold: 0.75
      hysteresis_lower_norm_threshold: 0.25


pl_dir_computer:
  pl_dir_computer:
    ros__parameters:
      vector_parallel_dot_prod_thresh: 0.95
      direction_computation_method: 3
      direction_computation_buffer_size: 20

pl_dir_estimator:
  pl_dir_estimator:
    ros__parameters:
      kf_q: 0.001
      kf_r: 0.999

pl_positions_computer:
  pl_positions_computer:
    ros__parameters:
      positions_computation_method: 2
      buffer_size: 10
      I: 120.
      cable_distance_max: 25.
      max_LMA_iterations: 100
      max_weighting_iterations: 1000
      lambda_first_step: 0.5
      lambda_increment_factor: 1.01
      lambda_decrement_factor: 0.9999
      step_norm_success_threshold: 1e-2

pl_positions_estimator:
  pl_positions_estimator:
    ros__parameters:
      kf_q: 0.001
      kf_r: 1.
      distance_discard_threshold: 4.

usb_cam:
  ros__parameters:
    video_device: "/dev/video0"
    framerate: 10.0
    io_method: "mmap"
    frame_id: "camera"
    pixel_format: "yuyv"
    image_width: 640
    image_height: 480
    camera_name: "test_camera"
    camera_info_url: "package://usb_cam/config/camera_info.yaml"

/**:
  ros__parameters:
    world_frame_id: "world"
    drone_frame_id: "drone"

    filename: "~/mag_samples.txt"

    n_periods: 20

    max_n_samples: 200

    I_min: 100
    I_max: 1000
    xyz_min: -10
    xyz_max: 10



